name: Build and package project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test with Gradle
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew bootJar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs
